"""empty message

Revision ID: 84ecd9f68ede
Revises: None
Create Date: 2017-01-22 17:10:44.517730

"""

# revision identifiers, used by Alembic.
revision = '84ecd9f68ede'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backpage', sa.Column('number_applications', sa.Integer(), nullable=True))
    op.drop_column('backpage', 'numer_applications')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backpage', sa.Column('numer_applications', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('backpage', 'number_applications')
    ### end Alembic commands ###
