"""empty message

Revision ID: 9b6f67afffe7
Revises: a1ccfceab8bb
Create Date: 2017-01-22 21:22:43.035518

"""

# revision identifiers, used by Alembic.
revision = '9b6f67afffe7'
down_revision = 'a1ccfceab8bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('prediction_type', sa.String(), nullable=True),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.Column('lower_bound', sa.Integer(), nullable=True),
    sa.Column('upper_bound', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('data', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trend')
    op.drop_table('prediction')
    ### end Alembic commands ###
