"""empty message

Revision ID: a1ccfceab8bb
Revises: 84ecd9f68ede
Create Date: 2017-01-22 17:18:58.677197

"""

# revision identifiers, used by Alembic.
revision = 'a1ccfceab8bb'
down_revision = '84ecd9f68ede'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('number_attendees', sa.Integer(), nullable=True),
    sa.Column('number_applications', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('backpage')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backpage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('number_attendees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number_applications', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='backpage_pkey')
    )
    op.drop_table('event_information')
    ### end Alembic commands ###
